### PR TITLE
Map new metadata fields to PG.

### PR DESCRIPTION
**Pull request by bjorntore**
Map new metadata fields to PG.

### CODE REVIEW

**Comment by bjorntore** [comment]
@SandGrainOne @acn-sbuad Må jeg gjøre noe mer for at disse to nye liste-propertiene på DataElement skal kunne skrives til? :)

**Comment by acn-sbuad** [comment]
LGTM, but @HenningNormann could maybe take a look? :)

**Comment by HenningNormann** [comment]
Jeg tror kanskje at merge logikken må gjøres mer komplisert siden det er snakk om felter som er komplekse datatyper. Ref. logikken i prosedyra for å oppdatere instance.

**Comment by HenningNormann** [comment]
@bjorntore @SandGrainOne @acn-sbuad I have added logic to serialize child properties of the new *metadata properties. I have also added some unit tests. It's important to define the semantics of the new functionality. With the suggested changes it will work by replacing existing metadata (existing metadata properties will be lost). If a merge of metadata properties is expected, the implementation is more complicated - ref update of instance. I assume replace/insert is what is needed, and in that case the PR is Ok from my view.

**Comment by HenningNormann** [comment]
Ser nå at unit test Altinn.Platform.Storage.UnitTest.TestingRepositories.TextTests.Text_Delete_Ok feiler i pipeline. Skjønner ikke hvorfor i farten. Funker lokalt hos meg og endringen burde ikke påvirke denne testen. Bruker ikke mer tid på å finne ut av dette nå som jeg har begynt ferien.

**Comment by acn-sbuad** [comment]
> Ser nå at unit test Altinn.Platform.Storage.UnitTest.TestingRepositories.TextTests.Text_Delete_Ok feiler i pipeline. Skjønner ikke hvorfor i farten. Funker lokalt hos meg og endringen burde ikke påvirke denne testen. Bruker ikke mer tid på å finne ut av dette nå som jeg har begynt ferien.

DB connections som er brukt opp her. Ikke noe funksjonelt feil. Trigger testen igjen.

**Comment by bjorntore** [comment]
> @bjorntore @SandGrainOne @acn-sbuad I have added logic to serialize child properties of the new *metadata properties. I have also added some unit tests. It's important to define the semantics of the new functionality. With the suggested changes it will work by replacing existing metadata (existing metadata properties will be lost). If a merge of metadata properties is expected, the implementation is more complicated - ref update of instance. I assume replace/insert is what is needed, and in that case the PR is Ok from my view.

Amazing! Thanks!

**Comment by acn-sbuad** [comment]
Omsider fått workflow til å kjøre igjen etter å ha justert max connections. @bjorntore den klager enda på coverage. Lager du noen tester som dekker user metadata med utgangspunkt i testene som Henning har lagt til allerede?

**Comment by HenningNormann** [comment]
@acn-sbuad Er endringene rundt connection life time nødvendige? Var det ikke kun mangel på connections som var problemet? Dette kan løses ved å øke max connections på server - slik du har gjort (eller ved å begrense max connections i connection string, men dette medfører at testene bruker lenger tid på å bli ferdige, så server løsningen er vel best).

**Review by acn-sbuad — APPROVED** [review]
🎈

**Comment by SandGrainOne** [comment]
### Testing
Decided to test the change a bit. This is the tests I performed.

1. Created an instance of apps-test in AT23.
  - Random TestId user: `17907798666` 
  - InstanceId: `50417182/b4e4efec-0ffb-47f2-a4ab-21c977178d1b`
  - DataElementId: `55b5692d-314d-4b47-8c79-a76c1c8d03b6`
  - InstancePath: `/instances/50417182/b4e4efec-0ffb-47f2-a4ab-21c977178d1b`
  - BlobPath: `/instances/50417182/b4e4efec-0ffb-47f2-a4ab-21c977178d1b/data/55b5692d-314d-4b47-8c79-a76c1c8d03b6`
  - DataElementPath: `/instances/50417182/b4e4efec-0ffb-47f2-a4ab-21c977178d1b/dataelements/55b5692d-314d-4b47-8c79-a76c1c8d03b6`
2. Switching to Postman.
3. There isn't any endpoint for getting a specific data element. Using GET instance which includes a list of data elements.
Original DataElement
```json
{
    "id": "55b5692d-314d-4b47-8c79-a76c1c8d03b6",
    "instanceGuid": "b4e4efec-0ffb-47f2-a4ab-21c977178d1b",
    "dataType": "default",
    "contentType": "application/xml",
    "blobStoragePath": "ttd/apps-test/b4e4efec-0ffb-47f2-a4ab-21c977178d1b/data/55b5692d-314d-4b47-8c79-a76c1c8d03b6",
    "selfLinks": {
        "platform": "https://platform.at23.altinn.cloud/storage/api/v1/instances/50417182/b4e4efec-0ffb-47f2-a4ab-21c977178d1b/data/55b5692d-314d-4b47-8c79-a76c1c8d03b6"
    },
    "size": 536,
    "locked": false,
    "isRead": true,
    "tags": [],
    "fileScanResult": "NotApplicable",
    "created": "2024-07-09T10:16:30.2945854Z",
    "createdBy": "20020486",
    "lastChanged": "2024-07-09T10:16:30.294585Z",
    "lastChangedBy": "20020486"
}
```

### Results
Crafting a few update requests.

**Test 1**
Request
```json
{
    "id": "55b5692d-314d-4b47-8c79-a76c1c8d03b6",
    "instanceGuid": "b4e4efec-0ffb-47f2-a4ab-21c977178d1b",
    "userDefinedMetadata": [
        {"myvalue": "yourvalue?!"},
        {"anothervalue": "soundsgood"}
    ]
}
```
Response:
```json
{
    "id": "55b5692d-314d-4b47-8c79-a76c1c8d03b6",
    "instanceGuid": "b4e4efec-0ffb-47f2-a4ab-21c977178d1b",
    "dataType": "default",
    "contentType": "application/xml",
    "blobStoragePath": "ttd/apps-test/b4e4efec-0ffb-47f2-a4ab-21c977178d1b/data/55b5692d-314d-4b47-8c79-a76c1c8d03b6",
    "size": 536,
    "locked": false,
    "isRead": true,
    "tags": [],
    "userDefinedMetadata": [
        {
            "key": null,
            "value": null
        },
        {
            "key": null,
            "value": null
        }
    ],
    "fileScanResult": "NotApplicable",
    "created": "2024-07-09T10:16:30.2945854Z",
    "createdBy": "20020486"
}
```

**Comment by SandGrainOne** [comment]
@bjorntore Is there something wrong with my request? The array is updated with correct number of entries, but the values aren't being persisted. Both the key and value ends up being null.

**Comment by SandGrainOne** [comment]
Basic testing concluded. Looks like it's working as advertised.

**Comment by SandGrainOne** [comment]
Another thing I notices is that the Tags property is never null. It's always a list and empty if there are no tags.

**Comment by bjorntore** [comment]
> Another thing I notices is that the Tags property is never null. It's always a list and empty if there are no tags.

I saw that as well when I was adding the new properties. Considered doing the same for this stuff to be consistent, but we discussed it in the PR and concluded that nullable was better in this case.

**Comment by bjorntore** [comment]
Tnx for well documented testing. 🙌

**Pull request merged**
