### PR TITLE
feat(TextResource): add defaultValue to TextResourceVariable

### PR DESCRIPTION
**Pull request by mikaelrss**
## Description

This PR adds support for a defaultValue option in variables in text resources. This would allow for app developers to provide a value to print if the variable points to a null-value in the datamodel. The current behavior is that the app displays the path to the datamodel.

## Related Issue(s)
- Altinn/app-frontend-react#1440
- Altinn/app-frontend-react#754

## Verification
- [x] **Your** code builds clean without any errors or warnings
- [x] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [x] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable) https://github.com/Altinn/altinn-studio-docs/pull/1134

### CODE REVIEW

**Comment by mikaelrss** [comment]
I'm a little unsure if this needs automated tests, and if so, how you would add meaningful tests to the new functionality.

**Comment by SandGrainOne** [comment]
@RonnyB71 Could you please take a look at this?

**Review by tjololo — APPROVED** [review]
Ser ut for meg som om dette er en god løsning på problemet som er meldt inn.
@nkylstad må dette synces med designer sånn at disse ikke fjernes om brukeren legger det til manuelt også oppdaterer text resursene i designer?

**Comment by TomasEng** [comment]
@tjololo, vi bør nok ta hensyn til dette i Studio, ja. Jeg oppretter en sak på det.

**Pull request merged**
